#!/usr/bin/env python3
"""
SEO YouTube Pipeline — Synergy Automation
==========================================
Finds YouTube videos on a topic → extracts transcripts → generates original
blog article → shows preview for approval → auto-publishes.

AI PROVIDER (pick one — default is Gemini Flash which is FREE):
  --ai gemini    Gemini 2.0 Flash (FREE, 1500 articles/day) ← DEFAULT
  --ai openai    GPT-4o-mini (~₹0.20/article)
  --ai claude    Claude claude-sonnet-4-6 (~₹4.50/article)

TRANSCRIPT STRATEGY (automatic, in order of priority):
  1. YouTube Transcript API — English captions (fastest)
  2. YouTube Transcript API — Hindi auto-captions (many Tally videos are Hindi-only)
  3. Gemini Video Analysis  — Gemini reads the YouTube video directly via URL
                              Works for captionless/Hindi videos. Free: 8 hrs/day.
  4. Title + description    — Last resort if all above fail

SETUP (one time):
  pip install google-api-python-client youtube-transcript-api google-genai

OPTIONAL (if using OpenAI or Claude instead):
  pip install openai anthropic

ENV VARS:
  YOUTUBE_API_KEY     — free: console.cloud.google.com → Enable YouTube Data API v3
  GEMINI_API_KEY      — free: aistudio.google.com → Get API key (no credit card)
  OPENAI_API_KEY      — optional: platform.openai.com (paid, ~₹0.20/article)
  ANTHROPIC_API_KEY   — optional: console.anthropic.com (paid, ~₹4.50/article)

USAGE:
  # Single topic (free Gemini)
  python scripts/seo_youtube_pipeline.py "bank reconciliation tally"

  # Single topic with specific AI
  python scripts/seo_youtube_pipeline.py "bank reconciliation tally" --ai openai

  # Process next topic from queue
  python scripts/seo_youtube_pipeline.py --queue

  # Publish a saved draft
  python scripts/seo_youtube_pipeline.py --publish scripts/seo_drafts/draft.js
"""

import os
import sys
import json
import re
import subprocess
import time
from datetime import date
from pathlib import Path

# ─────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────
REPO_ROOT        = Path(__file__).parent.parent
BLOG_DATA_FILE   = REPO_ROOT / 'src' / 'data' / 'blogData.js'
SITEMAP_FILE     = None   # auto-generated by sitemap.js — no manual update needed
PACKAGE_JSON     = None   # no reactSnap config in Next.js
QUEUE_FILE       = Path(__file__).parent / 'seo_topics_queue.txt'
DONE_FILE        = Path(__file__).parent / 'seo_topics_done.txt'
DRAFTS_DIR       = Path(__file__).parent / 'seo_drafts'
TODAY            = date.today().isoformat()
SITE_URL         = 'https://synergyfuturecorp.com'

YOUTUBE_API_KEY   = os.environ.get('YOUTUBE_API_KEY')
GEMINI_API_KEY    = os.environ.get('GEMINI_API_KEY')
OPENAI_API_KEY    = os.environ.get('OPENAI_API_KEY')
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY')

# Brand rules injected into every generation prompt
BRAND_RULES = """
BRAND RULES (non-negotiable):
- Product name: "Synergy Automation" — NEVER "Synergy Dashboard"
- NEVER name competitors — use "other tools", "XML converter tools", "paid platforms"
- No fake numbers (no "500+ CAs", "98% accuracy")
- LedgerMatch: NEVER mention — it is an internal develop-only feature
- Data honesty: say "your data is stored securely in our system" — NEVER "we don't store"
- Free claim: Synergy Automation is FREE — state this confidently
- Direct posting claim: "posts directly to Tally without XML files" — accurate, state confidently
- Supports: Tally Prime AND Tally ERP 9 — always mention both
""".strip()


# ─────────────────────────────────────────────
# STEP 1 — YOUTUBE SEARCH
# ─────────────────────────────────────────────
def search_videos(topic, max_results=5):
    try:
        from googleapiclient.discovery import build
    except ImportError:
        print("ERROR: Run: pip install google-api-python-client")
        sys.exit(1)

    if not YOUTUBE_API_KEY:
        print("ERROR: Set YOUTUBE_API_KEY environment variable")
        sys.exit(1)

    youtube = build('youtube', 'v3', developerKey=YOUTUBE_API_KEY)
    search_query = f"{topic} tally india"
    request = youtube.search().list(
        part='snippet',
        q=search_query,
        type='video',
        maxResults=max_results,
        relevanceLanguage='en',
        order='relevance',
        regionCode='IN'
    )
    response = request.execute()

    videos = []
    for item in response.get('items', []):
        vid_id = item['id'].get('videoId')
        if vid_id:
            videos.append({
                'id': vid_id,
                'title': item['snippet']['title'],
                'channel': item['snippet']['channelTitle'],
                'description': item['snippet']['description'][:300],
                'url': f'https://youtube.com/watch?v={vid_id}',
                'transcript': None
            })
    return videos


# ─────────────────────────────────────────────
# STEP 2 — GET TRANSCRIPTS
# ─────────────────────────────────────────────
def get_transcript(video_id, max_chars=5000):
    try:
        from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled, NoTranscriptFound
    except ImportError:
        print("ERROR: Run: pip install youtube-transcript-api")
        sys.exit(1)

    try:
        # Try English first, then Hindi auto-captions (common for Tally tutorial channels)
        try:
            transcript = YouTubeTranscriptApi.get_transcript(video_id, languages=['en'])
        except Exception:
            try:
                transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
                transcript = transcript_list.find_generated_transcript(['en', 'hi']).fetch()
            except Exception:
                return None

        text = ' '.join(t['text'] for t in transcript)
        # Clean auto-generated artifacts
        text = re.sub(r'\[.*?\]', '', text)
        text = re.sub(r'\s+', ' ', text).strip()
        return text[:max_chars]

    except Exception:
        return None


def get_content_via_gemini_video(video_id, video_title):
    """
    Gemini reads the YouTube video directly — no captions or download needed.
    Handles Hindi-only videos. Free tier: 8 hrs of video/day.
    Uses google-genai SDK (newer, supports from_uri for YouTube URLs).
    """
    try:
        from google import genai
        from google.genai import types
    except ImportError:
        return None

    if not GEMINI_API_KEY:
        return None

    video_url = f"https://www.youtube.com/watch?v={video_id}"
    client = genai.Client(api_key=GEMINI_API_KEY)

    for attempt in range(3):
        try:
            response = client.models.generate_content(
                model='gemini-2.5-flash-lite',
                contents=[
                    types.Part.from_uri(
                        file_uri=video_url,
                        mime_type='video/mp4',
                    ),
                    (
                        f"Video title: {video_title}\n"
                        "This is a Tally accounting tutorial for Indian CAs/accountants (may be in Hindi). "
                        "Extract all educational content and write it in clear English: the main topic, "
                        "every step of the process shown (with exact Tally menu paths and field names if "
                        "visible), shortcuts and tips mentioned, common mistakes discussed, and any Indian "
                        "accounting context (GST, ledger types, voucher types, etc.). "
                        "Write 400-600 words. Be specific — name exact buttons, menu items, and fields."
                    )
                ]
            )
            return response.text.strip()
        except Exception as e:
            err = str(e)
            if ('429' in err or '503' in err) and attempt < 2:
                wait = 30 + attempt * 30
                print(f"    Gemini video error ({err[:60]}) — retrying in {wait}s ({attempt+1}/3)...")
                time.sleep(wait)
            else:
                print(f"    Gemini video analysis error: {e}")
                return None


# ─────────────────────────────────────────────
# STEP 3 — BUILD PROMPT
# ─────────────────────────────────────────────
def build_prompt(topic, videos_with_transcript):
    research_text = ""
    for v in videos_with_transcript:
        research_text += f"\n\n--- VIDEO: {v['title']} (Channel: {v['channel']}) ---\n"
        research_text += v['transcript'][:2500]

    return f"""You are writing an SEO Knowledge Hub article for synergyfuturecorp.com about Synergy Automation.
This tool lets Indian CAs and accountants post Excel bank statements directly to Tally Prime and Tally ERP 9 — free, no XML files.

TOPIC: {topic}

{BRAND_RULES}

RESEARCH (YouTube transcripts — use as INSPIRATION for what to explain, write 100% original content):
{research_text}

─── WRITING STYLE ─────────────────────────────────────────────────────────────
- Simple English. Write like talking to a busy CA, not writing a textbook.
- Overview first, then detail. Give the answer in the first paragraph.
- Each section stands alone — no "as mentioned above" or "see below" references.
- Specific and actionable — say WHAT to click and WHERE, not just "reconcile your entries".
- Keep the reader moving: short sentences, clear steps, no filler phrases.

─── REQUIRED CONTENT STRUCTURE ────────────────────────────────────────────────
Follow these blocks IN THIS EXACT ORDER (do not add extra sections or reorder):

1. intro       — Hook: 1 sentence naming the exact pain. Then 2-3 sentences: what this covers + who benefits.
2. h2 + p      — "What is [Topic]" — plain-English explanation, 60-80 words, no jargon.
3. h2 + steps  — "How to [Primary Action] — Step by Step" — 4-6 numbered steps, each 1-2 clear sentences.
4. h2 + list   — "Common Mistakes to Avoid" — 3-5 specific mistakes Indian CAs actually make here.
5. h2 + p      — "How Synergy Automation Makes This Easier" — explain product value for this exact topic.
6. infographic — REQUIRED. Visual summary card. variant='steps' for process topics, 'checklist' for tips.
7. faq         — REQUIRED. 4-5 Q&As, self-contained answers (AI engines quote these directly).

─── OUTPUT FORMAT ─────────────────────────────────────────────────────────────
Return ONLY a valid JavaScript object (no export, no const, no markdown blocks — just the raw object).
Use single quotes for ALL strings. Escape apostrophes as \\'.

{{
  slug: 'url-slug-here',
  title: 'Title 55-60 Chars Including Year (2026)',
  tag: 'Guide',
  published: '{TODAY}',
  updated: '{TODAY}',
  description: '140-160 char meta description containing primary keyword. Complete sentence.',
  keywords: 'primary keyword, secondary keyword, tertiary keyword',
  content: [
    {{
      type: 'intro',
      text: 'Hook: one sentence naming the exact problem CAs face with this topic. Then 2-3 sentences on what you\\'ll learn here and who benefits most.'
    }},
    {{ type: 'h2', text: 'What is [Topic]' }},
    {{ type: 'p', text: 'Plain-English explanation in 60-80 words. No jargon. Define any technical terms.' }},
    {{ type: 'h2', text: 'How to [Primary Action] — Step by Step' }},
    {{ type: 'steps', items: [
      'Step 1: Do this specific thing — explain exactly how in one sentence.',
      'Step 2: Then do this — mention what to watch out for.',
      'Step 3: ...',
      'Step 4: ...'
    ]}},
    {{ type: 'h2', text: 'Common Mistakes to Avoid' }},
    {{ type: 'list', items: [
      'Mistake description: explain what goes wrong and the specific fix.',
      'Mistake description: ...',
      'Mistake description: ...'
    ]}},
    {{ type: 'h2', text: 'How Synergy Automation Makes This Easier' }},
    {{ type: 'p', text: 'Explain specifically — not generically — how Synergy Automation helps with THIS exact topic. Mention the relevant step from the guide above.' }},
    {{
      type: 'infographic',
      variant: 'steps',
      title: 'Process title: 6-8 words',
      items: [
        'Short step label (4-7 words)',
        'Short step label',
        'Short step label',
        'Short step label',
        'Short step label'
      ]
    }},
    {{
      type: 'faq',
      items: [
        {{ q: 'Question using primary keyword?', a: 'Self-contained 2-3 sentence answer. No "see above" — the answer must make sense alone. AI engines quote these directly.' }},
        {{ q: 'Second specific question Indian CAs ask?', a: 'Self-contained answer.' }},
        {{ q: 'Question about Synergy Automation for this topic?', a: 'Self-contained answer mentioning Synergy Automation and what it does here.' }},
        {{ q: 'Common concern or edge case?', a: 'Self-contained answer.' }},
        {{ q: 'Fifth question (optional but recommended)?', a: 'Self-contained answer.' }}
      ]
    }}
  ]
}}

─── CONTENT RULES ─────────────────────────────────────────────────────────────
- MANDATORY blocks: steps, infographic, faq — omitting any = invalid output
- Minimum 4 FAQ items, all self-contained (critical for GEO/AI engine citations)
- Mention "Synergy Automation" at least 3 times in body content
- Primary keyword in: title, first h2, and at least one FAQ question
- Include relevant Indian bank names (HDFC, SBI, ICICI, Axis, Kotak, etc.) where natural
- Features you MAY mention: Excel upload, review table, direct posting to Tally, ledger assignment
- NEVER mention: PDF upload, LedgerMatch, duplicate detection — these don\\'t exist or are dev-only
"""


# ─────────────────────────────────────────────
# STEP 3 — GENERATE ARTICLE (multi-provider)
# ─────────────────────────────────────────────
def generate_article(topic, videos_with_transcript, provider='gemini'):
    prompt = build_prompt(topic, videos_with_transcript)

    if provider == 'gemini':
        return _generate_gemini(prompt)
    elif provider == 'openai':
        return _generate_openai(prompt)
    elif provider == 'claude':
        return _generate_claude(prompt)
    else:
        print(f'Unknown provider: {provider}. Using gemini.')
        return _generate_gemini(prompt)


def _generate_gemini(prompt):
    """FREE — Gemini 1.5 Flash. 1,500 requests/day free tier. Get key: aistudio.google.com"""
    try:
        from google import genai
        from google.genai import types
    except ImportError:
        print("ERROR: Run: pip install google-genai")
        sys.exit(1)

    if not GEMINI_API_KEY:
        print("ERROR: Set GEMINI_API_KEY — get free key at aistudio.google.com (no credit card)")
        sys.exit(1)

    client = genai.Client(api_key=GEMINI_API_KEY)
    for attempt in range(3):
        try:
            response = client.models.generate_content(
                model='gemini-2.5-flash-lite',
                contents=prompt,
                config=types.GenerateContentConfig(max_output_tokens=4000, temperature=0.7)
            )
            return response.text.strip()
        except Exception as e:
            err = str(e)
            if ('429' in err or '503' in err) and attempt < 2:
                wait = 40 + attempt * 20
                print(f'  Gemini busy ({err[:60]}) — waiting {wait}s before retry ({attempt+1}/3)...')
                time.sleep(wait)
            else:
                print(f'ERROR: Gemini generation failed: {e}')
                sys.exit(1)


def _generate_openai(prompt):
    """~₹0.20/article — GPT-4o-mini"""
    try:
        from openai import OpenAI
    except ImportError:
        print("ERROR: Run: pip install openai")
        sys.exit(1)

    if not OPENAI_API_KEY:
        print("ERROR: Set OPENAI_API_KEY — get key at platform.openai.com")
        sys.exit(1)

    client = OpenAI(api_key=OPENAI_API_KEY)
    resp = client.chat.completions.create(
        model='gpt-4o-mini',
        max_tokens=4000,
        messages=[{'role': 'user', 'content': prompt}]
    )
    return resp.choices[0].message.content.strip()


def _generate_claude(prompt):
    """~₹4.50/article — Claude claude-sonnet-4-6 (best quality, most expensive)"""
    try:
        import anthropic
    except ImportError:
        print("ERROR: Run: pip install anthropic")
        sys.exit(1)

    if not ANTHROPIC_API_KEY:
        print("ERROR: Set ANTHROPIC_API_KEY — get key at console.anthropic.com")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    message = client.messages.create(
        model='claude-sonnet-4-6',
        max_tokens=4000,
        messages=[{'role': 'user', 'content': prompt}]
    )
    return message.content[0].text.strip()


# ─────────────────────────────────────────────
# STEP 4 — SHOW PREVIEW + GET APPROVAL
# ─────────────────────────────────────────────
def show_preview(topic, article_js, videos):
    print('\n' + '='*60)
    print(f'TOPIC: {topic}')
    print('RESEARCHED FROM:')
    for v in videos:
        icon = '✓' if v['transcript'] else '✗'
        print(f'  {icon} {v["title"][:70]}')
    print('='*60)
    print('\nGENERATED ARTICLE (preview):')
    print('-'*60)

    # Extract title and slug for quick review
    slug_match = re.search(r"slug:\s*'([^']+)'", article_js)
    title_match = re.search(r"title:\s*'([^']+)'", article_js)
    desc_match = re.search(r"description:\s*'([^']+)'", article_js)

    if slug_match:
        print(f'  URL:   /blog/{slug_match.group(1)}')
    if title_match:
        print(f'  Title: {title_match.group(1)}')
    if desc_match:
        print(f'  Desc:  {desc_match.group(1)[:100]}')

    print('\n--- FULL CONTENT ---')
    # Show first 1500 chars
    preview = article_js[:1500]
    print(preview)
    if len(article_js) > 1500:
        print(f'\n  ... ({len(article_js) - 1500} more chars) ...')
    print('-'*60)

    print('\nOptions:')
    print('  y      — Approve and publish to develop branch')
    print('  n      — Skip this topic')
    print('  s      — Save draft for manual editing')
    print('  r      — Regenerate article')

    return input('\nYour choice (y/n/s/r): ').strip().lower()


# ─────────────────────────────────────────────
# STEP 5 — PUBLISH
# ─────────────────────────────────────────────
def publish_article(article_js, commit=True):
    """Write article to all files. commit=False skips git (GitHub Actions commits separately)."""
    slug_match = re.search(r"slug:\s*'([^']+)'", article_js)
    if not slug_match:
        print('ERROR: Cannot find slug in article. Save as draft and check manually.')
        return False

    slug = slug_match.group(1)
    print(f'\nWriting /blog/{slug} to files...')

    # ── blogData.js ──
    blog_data = BLOG_DATA_FILE.read_text(encoding='utf-8')
    if blog_data.rstrip().endswith('];'):
        new_blog_data = blog_data.rstrip()[:-2].rstrip()
        if not new_blog_data.rstrip().endswith(','):
            new_blog_data += ','
        new_blog_data += f'\n  {article_js}\n];\n'
        BLOG_DATA_FILE.write_text(new_blog_data, encoding='utf-8')
        print('  ✓ blogData.js updated')
    else:
        print('  ERROR: blogData.js format unexpected. Save as draft.')
        return False

    # sitemap.js auto-generates from blogData.js — no manual update needed

    if not commit:
        print(f'  ✓ Files written. Slug: {slug}')
        # Write slug to a file so the GitHub Actions step can read it
        (REPO_ROOT / '.seo_last_slug').write_text(slug, encoding='utf-8')
        return True

    # ── git commit (local use only) ──
    files = [
        str(BLOG_DATA_FILE),
    ]
    subprocess.run(['git', 'add'] + files, cwd=REPO_ROOT, check=True)
    commit_msg = f'feat(seo): add {slug} article via YouTube pipeline'
    result = subprocess.run(
        ['git', 'commit', '-m', commit_msg],
        cwd=REPO_ROOT, capture_output=True, text=True
    )
    if result.returncode == 0:
        print(f'  ✓ Committed: {commit_msg}')
    else:
        print(f'  WARNING: git commit issue: {result.stderr}')

    print(f'\n✅ Done! /blog/{slug} is ready.')
    print('Next step: git push origin develop')
    print('Then merge develop → main to go live on Netlify.')
    return True


# ─────────────────────────────────────────────
# DRAFT SAVE / PUBLISH FROM DRAFT
# ─────────────────────────────────────────────
def save_draft(topic, article_js):
    DRAFTS_DIR.mkdir(exist_ok=True)
    safe_topic = re.sub(r'[^a-z0-9]+', '-', topic.lower()).strip('-')
    draft_path = DRAFTS_DIR / f'draft-{safe_topic}.js'
    draft_path.write_text(article_js, encoding='utf-8')
    print(f'\nDraft saved: {draft_path}')
    print('Edit it, then run:')
    print(f'  python scripts/seo_youtube_pipeline.py --publish "{draft_path}"')


def publish_from_draft(draft_path):
    path = Path(draft_path)
    if not path.exists():
        print(f'ERROR: Draft not found: {draft_path}')
        sys.exit(1)
    article_js = path.read_text(encoding='utf-8').strip()
    success = publish_article(article_js)
    if success:
        path.unlink()
        print('Draft file removed after publish.')


# ─────────────────────────────────────────────
# TOPIC QUEUE (for daily/recurring use)
# ─────────────────────────────────────────────
def get_next_topic_from_queue():
    if not QUEUE_FILE.exists():
        print(f'No queue file found at {QUEUE_FILE}')
        print('Create it with one topic per line.')
        sys.exit(1)

    done = set()
    if DONE_FILE.exists():
        done = set(DONE_FILE.read_text(encoding='utf-8').splitlines())

    topics = [
        line.strip()
        for line in QUEUE_FILE.read_text(encoding='utf-8').splitlines()
        if line.strip() and not line.startswith('#') and line.strip() not in done
    ]

    if not topics:
        print('All topics in queue have been processed.')
        print(f'Add more topics to {QUEUE_FILE}')
        sys.exit(0)

    return topics[0]


def mark_topic_done(topic):
    with open(DONE_FILE, 'a', encoding='utf-8') as f:
        f.write(topic + '\n')


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────
def run_pipeline(topic, provider='gemini', auto=False):
    """
    auto=True  — no interactive prompt, just write files (used by GitHub Actions).
                 Caller is responsible for committing/PR after this returns True.
    auto=False — interactive y/n/s/r approval (local use).
    """
    print(f'\n🔍 Searching YouTube: "{topic} tally india" ...')
    videos = search_videos(topic, max_results=6)

    if not videos:
        print('No videos found. Try a different topic.')
        return False

    print(f'Found {len(videos)} videos. Fetching transcripts...')
    for v in videos:
        v['transcript'] = get_transcript(v['id'])
        icon = '✓' if v['transcript'] else '✗'
        print(f'  {icon} {v["title"][:65]}')

    usable = [v for v in videos if v['transcript']]
    if not usable:
        # Stage 3: Gemini reads each YouTube video directly (handles Hindi, no captions needed)
        print('No captions found. Trying Gemini direct video analysis...')
        for v in videos[:1]:  # 1 video — keeps per-minute token usage low for article generation
            print(f'  Analyzing: {v["title"][:60]}...')
            content = get_content_via_gemini_video(v['id'], v['title'])
            if content:
                v['transcript'] = content
                print(f'    ✓ {len(content)} chars extracted by Gemini')
            else:
                # Stage 4: Last resort — title + description only
                v['transcript'] = f"Video title: {v['title']}\nDescription: {v['description']}"
                print(f'    ✗ Using title/description only')
        usable = [v for v in videos if v.get('transcript')]

    print(f'\n✍️  Generating article via {provider} from {len(usable)} video(s)...')
    article_js = generate_article(topic, usable, provider=provider)

    if auto:
        # Non-interactive: write files, skip git commit (GitHub Actions handles that)
        return publish_article(article_js, commit=False)

    while True:
        choice = show_preview(topic, article_js, videos)

        if choice == 'y':
            success = publish_article(article_js)
            return success

        elif choice == 'n':
            print('Skipped.')
            return False

        elif choice == 's':
            save_draft(topic, article_js)
            return False

        elif choice == 'r':
            print('\n♻️  Regenerating...')
            article_js = generate_article(topic, usable, provider=provider)

        else:
            print('Invalid choice. Enter y / n / s / r')


def main():
    args = sys.argv[1:]

    # Parse --ai <provider> flag
    provider = 'gemini'
    if '--ai' in args:
        idx = args.index('--ai')
        if idx + 1 < len(args):
            provider = args[idx + 1]
            args = [a for i, a in enumerate(args) if i != idx and i != idx + 1]

    # Parse --auto flag (non-interactive, used by GitHub Actions)
    auto = '--auto' in args
    if auto:
        args = [a for a in args if a != '--auto']

    print(f'AI provider: {provider}{"  [AUTO MODE]" if auto else ""}')

    # --publish path/to/draft.js
    if args and args[0] == '--publish':
        if len(args) < 2:
            print('Usage: python seo_youtube_pipeline.py --publish path/to/draft.js')
            sys.exit(1)
        publish_from_draft(args[1])
        return

    # --queue  (pick next topic from queue file)
    if args and args[0] == '--queue':
        topic = get_next_topic_from_queue()
        print(f'📋 Next topic from queue: "{topic}"')
        success = run_pipeline(topic, provider=provider, auto=auto)
        if success:
            mark_topic_done(topic)
        return

    # Direct topic from command line
    if args:
        topic = ' '.join(args)
    else:
        topic = input('Enter topic: ').strip()

    if not topic:
        print('No topic provided.')
        sys.exit(1)

    run_pipeline(topic, provider=provider, auto=auto)


if __name__ == '__main__':
    main()
