#!/usr/bin/env python3
"""
SEO YouTube Pipeline — Synergy Automation
==========================================
Finds YouTube videos on a topic → extracts transcripts → generates original
blog article → shows preview for approval → auto-publishes.

AI PROVIDER (pick one — default is Gemini Flash which is FREE):
  --ai gemini    Gemini 2.0 Flash (FREE, 1500 articles/day) ← DEFAULT
  --ai openai    GPT-4o-mini (~₹0.20/article)
  --ai claude    Claude claude-sonnet-4-6 (~₹4.50/article)

TRANSCRIPT STRATEGY (automatic, in order of priority):
  1. YouTube Transcript API — English captions (instant, no download)
  2. YouTube Transcript API — Hindi auto-captions (many Tally videos are Hindi-only)
  3. Audio Download         — yt-dlp downloads audio-only → Gemini Files API analyzes
                              Works for any video length (no frame limit). No FFmpeg needed.
  4. Title + description    — Last resort if audio download also fails

SETUP (one time):
  pip install google-api-python-client youtube-transcript-api google-genai yt-dlp

OPTIONAL (if using OpenAI or Claude instead):
  pip install openai anthropic

ENV VARS:
  YOUTUBE_API_KEY     — free: console.cloud.google.com → Enable YouTube Data API v3
  GEMINI_API_KEY      — free: aistudio.google.com → Get API key (no credit card)
  OPENAI_API_KEY      — optional: platform.openai.com (paid, ~₹0.20/article)
  ANTHROPIC_API_KEY   — optional: console.anthropic.com (paid, ~₹4.50/article)

USAGE:
  # Single topic (free Gemini)
  python scripts/seo_youtube_pipeline.py "bank reconciliation tally"

  # Single topic with specific AI
  python scripts/seo_youtube_pipeline.py "bank reconciliation tally" --ai openai

  # Process next topic from queue
  python scripts/seo_youtube_pipeline.py --queue

  # Publish a saved draft
  python scripts/seo_youtube_pipeline.py --publish scripts/seo_drafts/draft.js
"""

import os
import sys
import json
import re
import subprocess
import time
from datetime import date
from pathlib import Path

# Load .env file if present (local development)
_env_file = Path(__file__).parent.parent / '.env'
if _env_file.exists():
    for _line in _env_file.read_text(encoding='utf-8').splitlines():
        _line = _line.strip()
        if _line and not _line.startswith('#') and '=' in _line:
            _k, _, _v = _line.partition('=')
            os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))

# ─────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────
REPO_ROOT        = Path(__file__).parent.parent
BLOG_DATA_FILE   = REPO_ROOT / 'src' / 'data' / 'blogData.js'
SITEMAP_FILE     = None   # auto-generated by sitemap.js — no manual update needed
PACKAGE_JSON     = None   # no reactSnap config in Next.js
QUEUE_FILE       = Path(__file__).parent / 'seo_topics_queue.txt'
DONE_FILE        = Path(__file__).parent / 'seo_topics_done.txt'
DRAFTS_DIR       = Path(__file__).parent / 'seo_drafts'
TODAY            = date.today().isoformat()
SITE_URL         = 'https://synergyfuturecorp.com'
TALLY_VERSION    = 'TallyPrime 6.0'   # update when Tally releases a new version
GEMINI_MODEL     = 'gemini-2.5-flash-lite'

# Topics that Synergy directly solves → use 'product' article mode
PRODUCT_TOPIC_KEYWORDS = [
    'bank statement', 'excel to tally', 'excel bank', 'bank reconcil',
    'import statement', 'bank entry', 'bank import', 'statement to tally',
    'bank posting', 'bank ledger entry',
]

# Trending YouTube search seeds — used by --trending flag
TRENDING_QUERIES = [
    f'tally prime {date.today().year} tutorial',
    f'gst tally prime {date.today().year}',
    'tally prime new feature india',
    'tally erp accounting india latest',
    f'tds gst tally {date.today().year}',
]

YOUTUBE_API_KEY   = os.environ.get('YOUTUBE_API_KEY')
GEMINI_API_KEY    = os.environ.get('GEMINI_API_KEY')
OPENAI_API_KEY    = os.environ.get('OPENAI_API_KEY')
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY')

# Brand rules injected into every generation prompt
BRAND_RULES = """
BRAND RULES (non-negotiable):
- Product name: "Synergy Automation" — NEVER "Synergy Dashboard"
- NEVER name competitors — use "other tools", "XML converter tools", "paid platforms"
- No fake numbers (no "500+ CAs", "98% accuracy")
- LedgerMatch: NEVER mention — it is an internal develop-only feature
- Data honesty: say "your data is stored securely in our system" — NEVER "we don't store"
- Free claim: Synergy Automation is FREE — state this confidently
- Direct posting claim: "posts directly to Tally without XML files" — accurate, state confidently
- Supports: Tally Prime AND Tally ERP 9 — always mention both
""".strip()


# ─────────────────────────────────────────────
# STEP 1 — YOUTUBE SEARCH
# ─────────────────────────────────────────────
def search_videos(topic, max_results=5):
    try:
        from googleapiclient.discovery import build
    except ImportError:
        print("ERROR: Run: pip install google-api-python-client")
        sys.exit(1)

    if not YOUTUBE_API_KEY:
        print("ERROR: Set YOUTUBE_API_KEY environment variable")
        sys.exit(1)

    youtube = build('youtube', 'v3', developerKey=YOUTUBE_API_KEY)
    search_query = f"{topic} tally india"
    request = youtube.search().list(
        part='snippet',
        q=search_query,
        type='video',
        maxResults=max_results,
        relevanceLanguage='en',
        order='relevance',
        regionCode='IN'
    )
    response = request.execute()

    videos = []
    for item in response.get('items', []):
        vid_id = item['id'].get('videoId')
        if vid_id:
            videos.append({
                'id': vid_id,
                'title': item['snippet']['title'],
                'channel': item['snippet']['channelTitle'],
                'description': item['snippet']['description'][:300],
                'url': f'https://youtube.com/watch?v={vid_id}',
                'transcript': None
            })
    return videos


def _clean_topic(title):
    """Extract a clean topic string from a YouTube video title."""
    t = re.sub(r'#\w+', '', title)
    t = re.sub(r'\|.*$', '', t)
    t = re.sub(r'^\s*\d+[\.\)]\s*', '', t)
    t = re.sub(r'\s+', ' ', t).strip()
    if len(t) > 80:
        t = t[:80].rsplit(' ', 1)[0]
    return t


def get_trending_topic():
    """
    Discover trending topic from recent high-view Tally/accounting YouTube videos.
    Searches multiple seed queries, skips topics already in done list,
    returns the first fresh topic found.
    """
    try:
        from googleapiclient.discovery import build
        from datetime import timedelta
    except ImportError:
        return None

    if not YOUTUBE_API_KEY:
        print('No YOUTUBE_API_KEY -- cannot discover trending topics.')
        return None

    # Load done topics so we don't re-generate articles
    done = set()
    if DONE_FILE.exists():
        done = {ln.strip().lower() for ln in DONE_FILE.read_text(encoding='utf-8').splitlines() if ln.strip()}

    # Also skip slugs already in blogData.js
    if BLOG_DATA_FILE.exists():
        blog_content = BLOG_DATA_FILE.read_text(encoding='utf-8')
    else:
        blog_content = ''

    youtube = build('youtube', 'v3', developerKey=YOUTUBE_API_KEY)
    published_after = (date.today() - timedelta(days=60)).isoformat() + 'T00:00:00Z'

    seen_ids = set()
    candidates = []

    for query in TRENDING_QUERIES[:5]:   # up to 5 queries for wider discovery
        try:
            resp = youtube.search().list(
                part='snippet',
                q=query,
                type='video',
                maxResults=8,
                order='viewCount',
                publishedAfter=published_after,
                regionCode='IN',
            ).execute()
            for item in resp.get('items', []):
                vid_id = item['id'].get('videoId')
                if vid_id and vid_id not in seen_ids:
                    seen_ids.add(vid_id)
                    title = item['snippet']['title']
                    channel = item['snippet']['channelTitle']
                    # Skip Tally Solutions promos and broad course/playlist videos
                    broad_terms = ['complete course', 'full course', 'full tutorial', 'complete tutorial',
                                   'complete guide for beginners', 'part 1', 'part 2', 'part 3',
                                   'episode', 'ep.', 'ep ']
                    title_lower = title.lower()
                    if ('tally solution' not in channel.lower()
                            and not any(t in title_lower for t in broad_terms)):
                        candidates.append({'id': vid_id, 'title': title, 'channel': channel})
        except Exception as e:
            print(f'  Warning: trending search failed for "{query}": {e}')

    if not candidates:
        return None

    # Pick first candidate whose topic is not already done
    for cand in candidates:
        topic = _clean_topic(cand['title'])
        if topic.lower() in done:
            print(f'  Skip (done): "{topic[:60]}"')
            continue
        # Also skip if a very similar slug already exists in blogData.js
        slug_hint = topic.lower()[:25].replace(' ', '-')
        if slug_hint in blog_content:
            print(f'  Skip (slug exists): "{topic[:60]}"')
            continue
        print(f'  Trending video: "{cand["title"][:65]}" -- {cand["channel"]}')
        print(f'  Topic: "{topic}"')
        return topic

    print('  All trending topics already covered. Falling back to queue.')
    return None


def detect_article_mode(topic):
    """
    'product' — topic directly relates to what Synergy Automation does.
                 Article features Synergy prominently.
    'knowledge' — educational/informational topic.
                 Article is pure knowledge, light or no product mention.
    Roughly 1 in 4 articles should be product mode; knowledge builds trust and traffic.
    """
    t = topic.lower()
    if any(kw in t for kw in PRODUCT_TOPIC_KEYWORDS):
        return 'product'
    return 'knowledge'


# ─────────────────────────────────────────────
# STEP 2 — GET TRANSCRIPTS
# ─────────────────────────────────────────────
def get_transcript(video_id, max_chars=5000):
    try:
        from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled, NoTranscriptFound
    except ImportError:
        print("ERROR: Run: pip install youtube-transcript-api")
        sys.exit(1)

    try:
        # Try English first, then Hindi auto-captions (common for Tally tutorial channels)
        try:
            transcript = YouTubeTranscriptApi.get_transcript(video_id, languages=['en'])
        except Exception:
            try:
                transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
                transcript = transcript_list.find_generated_transcript(['en', 'hi']).fetch()
            except Exception:
                return None

        text = ' '.join(t['text'] for t in transcript)
        # Clean auto-generated artifacts
        text = re.sub(r'\[.*?\]', '', text)
        text = re.sub(r'\s+', ' ', text).strip()
        return text[:max_chars]

    except Exception:
        return None


def get_content_via_gemini_video(video_id, video_title):
    """
    Gemini reads the YouTube video directly — no captions or download needed.
    Handles Hindi-only videos. Free tier: 8 hrs of video/day.
    Uses google-genai SDK (newer, supports from_uri for YouTube URLs).
    """
    try:
        from google import genai
        from google.genai import types
    except ImportError:
        return None

    if not GEMINI_API_KEY:
        return None

    video_url = f"https://www.youtube.com/watch?v={video_id}"
    client = genai.Client(api_key=GEMINI_API_KEY)

    for attempt in range(3):
        try:
            response = client.models.generate_content(
                model='gemini-2.5-flash-lite',
                contents=[
                    types.Part.from_uri(
                        file_uri=video_url,
                        mime_type='video/mp4',
                    ),
                    (
                        f"Video title: {video_title}\n"
                        "This is a Tally accounting tutorial for Indian CAs/accountants (may be in Hindi). "
                        "Extract all educational content and write it in clear English: the main topic, "
                        "every step of the process shown (with exact Tally menu paths and field names if "
                        "visible), shortcuts and tips mentioned, common mistakes discussed, and any Indian "
                        "accounting context (GST, ledger types, voucher types, etc.). "
                        "Write 400-600 words. Be specific — name exact buttons, menu items, and fields."
                    )
                ]
            )
            return response.text.strip()
        except Exception as e:
            err = str(e)
            if ('429' in err or '503' in err) and attempt < 2:
                wait = 30 + attempt * 30
                print(f"    Gemini video error ({err[:60]}) — retrying in {wait}s ({attempt+1}/3)...")
                time.sleep(wait)
            else:
                print(f"    Gemini video analysis error: {e}")
                return None


def get_audio_transcript_gemini(video_id, video_title):
    """
    Download audio-only with yt-dlp → upload to Gemini Files API → extract key points.
    Avoids the 10,800-frame limit that blocks long videos in direct video analysis.
    No FFmpeg needed — downloads native webm/m4a format from YouTube.
    Requires: pip install yt-dlp
    """
    try:
        import yt_dlp
    except ImportError:
        print('    Audio fallback skipped — run: pip install yt-dlp')
        return None

    try:
        from google import genai
        from google.genai import types
    except ImportError:
        return None

    if not GEMINI_API_KEY:
        return None

    import tempfile
    import glob as _glob

    url = f'https://www.youtube.com/watch?v={video_id}'

    with tempfile.TemporaryDirectory() as tmpdir:
        out_template = os.path.join(tmpdir, f'{video_id}.%(ext)s')

        base_opts = {
            'format': 'bestaudio[ext=webm]/bestaudio[ext=m4a]/bestaudio',
            'outtmpl': out_template,
            'quiet': True,
            'no_warnings': True,
            'noprogress': True,
        }

        print('    Downloading audio...')

        # Attempt 1: direct (works for most videos)
        try:
            with yt_dlp.YoutubeDL(base_opts) as ydl:
                ydl.download([url])
        except Exception:
            pass

        matches = _glob.glob(os.path.join(tmpdir, f'{video_id}.*'))

        # Attempt 2: retry with Chrome cookies (bypasses 403 on protected videos)
        if not matches:
            print('    Blocked — retrying with Chrome cookies...')
            try:
                cookie_opts = {**base_opts, 'cookiesfrombrowser': ('chrome',)}
                with yt_dlp.YoutubeDL(cookie_opts) as ydl:
                    ydl.download([url])
                matches = _glob.glob(os.path.join(tmpdir, f'{video_id}.*'))
            except Exception as e:
                print(f'    Audio download failed: {e}')
                return None

        if not matches:
            print('    Audio file not found after download')
            return None

        audio_path = matches[0]
        ext = audio_path.rsplit('.', 1)[-1].lower()
        size_mb = os.path.getsize(audio_path) / (1024 * 1024)
        print(f'    Audio: {size_mb:.1f} MB ({ext})')

        mime_map = {
            'webm': 'audio/webm',
            'm4a': 'audio/mp4',
            'mp4': 'audio/mp4',
            'mp3': 'audio/mp3',
            'ogg': 'audio/ogg',
            'opus': 'audio/webm',
            'wav': 'audio/wav',
        }
        mime_type = mime_map.get(ext, 'audio/webm')

        client = genai.Client(api_key=GEMINI_API_KEY)

        try:
            print('    Uploading to Gemini...')
            uploaded = client.files.upload(
                file=audio_path,
                config=types.UploadFileConfig(mime_type=mime_type),
            )

            # Wait for Gemini to finish processing the audio file (usually <10s)
            for _ in range(20):
                file_info = client.files.get(name=uploaded.name)
                if file_info.state.name == 'ACTIVE':
                    break
                if file_info.state.name == 'FAILED':
                    print('    Gemini file processing failed')
                    return None
                time.sleep(3)

            prompt = (
                f'Video title: "{video_title}"\n'
                'This is audio from a YouTube Tally/accounting tutorial for Indian CAs '
                '(may be in Hindi or English). '
                'Extract all useful educational content: the main topic, every step of the '
                'process demonstrated (with exact Tally menu paths and field names if mentioned), '
                'shortcuts and tips, common mistakes discussed, and any Indian accounting context '
                '(GST, TDS, voucher types, ledger names, etc.). '
                'Write 400-600 words of structured notes in English. Be specific — '
                'name exact buttons, menu items, and fields.'
            )

            result = None
            for attempt in range(3):
                try:
                    resp = client.models.generate_content(
                        model=GEMINI_MODEL,
                        contents=[uploaded, prompt],
                    )
                    result = resp.text.strip()
                    break
                except Exception as e:
                    err = str(e)
                    if ('429' in err or '503' in err) and attempt < 2:
                        wait = 30 + attempt * 30
                        print(f'    Gemini busy ({err[:50]}) — retrying in {wait}s...')
                        time.sleep(wait)
                    else:
                        print(f'    Gemini audio error: {e}')
                        break

            # Clean up the uploaded file from Gemini storage
            try:
                client.files.delete(name=uploaded.name)
            except Exception:
                pass

            return result

        except Exception as e:
            print(f'    Gemini audio error: {e}')
            return None


# ─────────────────────────────────────────────
# STEP 3 — BUILD PROMPT
# ─────────────────────────────────────────────
def build_prompt(topic, videos_with_transcript, mode='knowledge'):
    research_text = ""
    for v in videos_with_transcript:
        research_text += f"\n\n--- VIDEO: {v['title']} (Channel: {v['channel']}) ---\n"
        research_text += v['transcript'][:2500]

    # ── shared context injected into both modes ──────────────────────────────
    shared_context = f"""TODAY: {TODAY}  |  Current Tally version: {TALLY_VERSION}  |  Site: synergyfuturecorp.com

TOPIC: {topic}
ARTICLE MODE: {mode.upper()}

{BRAND_RULES}

RESEARCH (from YouTube — use as INSPIRATION only, write 100% original content):
{research_text}

━━━ WRITING RULES (both modes) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Reference today's date ({TODAY}) and current year where relevant
- All Tally references: use "{TALLY_VERSION}" as primary, mention "Tally ERP 9" where relevant
- Sentences: max 20 words. Paragraphs: max 3 sentences.
- NO filler openers: never "In today\\'s world", "Managing finances", "As a CA"
- NO vague claims: never "saves time", "easy to use", "powerful" — always be SPECIFIC
- Numbers beat adjectives: "3 hours → 8 minutes" beats "much faster"
- Exact Tally paths: "Gateway of Tally > Display More Reports > ..." beats "open the report"
- Indian context: GST 20th deadline, advance tax quarters (Jun/Sep/Dec/Mar), TDS 7th, year-end March 31
- Named banks where natural: HDFC, SBI, ICICI, Axis, Kotak, PNB, Bank of Baroda
- Second person ("you", "your") throughout — feels like advice from a senior CA
- FAQ answers: self-contained, direct — like a WhatsApp reply, not a textbook paragraph

━━━ SCOPE RULE — ONE TASK, NOT A WHOLE COURSE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This article covers ONE specific task or workflow within "{topic}" — not everything about it.
A "complete course" has 20 videos. This article = ONE of those 20 videos, done deeply.
GOOD scope: "How to configure TDS Nature of Payment in TallyPrime 6.0"
BAD scope:  "Complete guide to TDS in Tally" (too broad)
Pick the most actionable, searchable sub-task from the research and go deep on it.

━━━ ANTI-DUPLICATE RULE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This article MUST cover a unique angle on "{topic}". Do not repeat generic steps any CA already knows.
Focus on the specific insight, shortcut, or mistake that is not obvious.
If the research covers a specific {TALLY_VERSION} feature, lead with that — it is newer and more valuable.

━━━ OUTPUT FORMAT (both modes) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Return ONLY a valid JavaScript object — no markdown fences, no export, no const, no explanation.
Raw object only: starts with {{ ends with }}.
Single quotes for ALL strings. Escape apostrophes as \\'.
"""

    # ── KNOWLEDGE MODE — education-first, no forced product section ───────────
    if mode == 'knowledge':
        return f"""You are a senior CA writing a knowledge-base article for synergyfuturecorp.com.
Your job is to give Indian CAs genuinely useful, deep knowledge — not to sell anything.
A reader should finish this article feeling smarter and grateful, not sold to.

{shared_context}

━━━ CONTENT STRUCTURE (knowledge mode) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. intro — Open with the specific scenario where this knowledge matters most.
   Name the exact deadline, workflow moment, or frustration. 3-4 sentences.
   End with: what the reader will know by the end of this article.

2. h2 + p — "What is [Topic]?" — 60-80 words. Plain English. One analogy.

3. h2 + steps — "How to [Primary Action] in {TALLY_VERSION} — Step by Step"
   5-7 steps. Each step: exact action + one embedded "Tally tip:" or "Watch out:".
   Include actual {TALLY_VERSION} menu paths.

4. h2 + list — "Mistakes That Cost Indian CAs Hours"
   4-5 specific mistakes. Name the mistake → what breaks → exact fix.

5. h2 + p — "Pro Tips for {date.today().year}" (optional Synergy mention here — max 1 sentence, natural fit only)
   2-3 insider tips that go beyond the basic steps. Things CAs learn after months of doing this.

6. infographic — Visual summary (variant: \\'steps\\' or \\'checklist\\').

7. faq — 5 Q&As. Questions = real searches Indian CAs type into Google or ask ChatGPT.
   Include "How to do [topic] in {TALLY_VERSION}?" as one question.

━━━ KNOWLEDGE MODE CHECKS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- steps: 5+ items with specific Tally paths ✓
- infographic present ✓
- faq: 5 items, all self-contained ✓
- "Synergy Automation" mentioned 0-1 times maximum (not forced) ✓
- No vague phrases: "saves time", "powerful", "seamless" ✗
- No forbidden: PDF upload, LedgerMatch, duplicate detection ✗
- Primary keyword in title + at least 1 FAQ question ✓
- Today\\'s date ({TODAY}) and {TALLY_VERSION} referenced ✓

{{
  slug: 'descriptive-slug-topic-focus',
  title: 'Specific Title 55-65 Chars — {TALLY_VERSION} + {date.today().year}',
  tag: 'Guide',
  published: '{TODAY}',
  updated: '{TODAY}',
  description: '140-160 char meta. Primary keyword first. Specific benefit. Ends with period.',
  keywords: 'primary keyword, secondary keyword, long-tail keyword india',
  content: [
    {{ type: 'intro', text: 'Specific scenario. Deadline. Pain. What you learn here.' }},
    {{ type: 'h2', text: 'What is [Topic]?' }},
    {{ type: 'p', text: '60-80 words. Plain English. Analogy.' }},
    {{ type: 'h2', text: 'How to [Action] in {TALLY_VERSION} — Step by Step' }},
    {{ type: 'steps', items: ['Step with exact path. Tally tip: ...', 'Step. Watch out: ...', '...', '...', '...'] }},
    {{ type: 'h2', text: 'Mistakes That Cost Indian CAs Hours' }},
    {{ type: 'list', items: ['Mistake: what breaks → fix', '...', '...', '...'] }},
    {{ type: 'h2', text: 'Pro Tips for {date.today().year}' }},
    {{ type: 'p', text: '2-3 insider tips. One optional natural Synergy mention if it genuinely fits.' }},
    {{ type: 'infographic', variant: 'steps', title: 'Process title 5-7 words', items: ['Label', 'Label', 'Label', 'Label', 'Label'] }},
    {{ type: 'faq', items: [
      {{ q: 'How to do [topic] in {TALLY_VERSION}?', a: 'Self-contained 2-3 sentence answer.' }},
      {{ q: 'Real question CAs Google?', a: 'Self-contained answer.' }},
      {{ q: 'Common mistake question?', a: 'Self-contained answer with fix.' }},
      {{ q: '[Topic] in Tally ERP 9 vs {TALLY_VERSION}?', a: 'Self-contained answer.' }},
      {{ q: 'Time/effort question?', a: 'Self-contained with realistic estimate.' }}
    ]}}
  ]
}}
"""

    # ── PRODUCT MODE — Synergy Automation is the hero ─────────────────────────
    return f"""You are a senior content writer for synergyfuturecorp.com.
Synergy Automation is a FREE tool that lets Indian CAs post Excel bank statements directly to {TALLY_VERSION} and Tally ERP 9 — no XML files, no manual entry.
This article shows how Synergy solves a real CA pain point.

{shared_context}

━━━ CONTENT STRUCTURE (product mode) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. intro — The specific painful moment this topic creates. 3-4 sentences. End with: Synergy Automation solves this.

2. h2 + p — "What is [Topic]?" — 60-80 words. Plain English.

3. h2 + steps — "How to [Action] in {TALLY_VERSION} — Step by Step" — 5-7 steps with exact paths.

4. h2 + list — "Mistakes That Cost Indian CAs Hours" — 4-5 specific mistakes + fixes.

5. h2 + p — "How Synergy Automation Handles This" — Connect to the hardest step above.
   Specific: upload Excel → review entries → post to Tally. Free. No XML. Works with {TALLY_VERSION} and ERP 9.

6. infographic — Visual summary.

7. faq — 5 Q&As. One must be about Synergy Automation for this topic.

━━━ PRODUCT MODE CHECKS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- steps: 5+ items ✓ | infographic ✓ | faq: 5 items ✓
- "Synergy Automation" 3+ times ✓
- Synergy section connects to a specific step above (not generic) ✓
- No vague: "saves time", "powerful", "seamless" ✗
- No forbidden: PDF upload, LedgerMatch, duplicate detection ✗
- Primary keyword in title + 1 FAQ ✓ | date {TODAY} + {TALLY_VERSION} referenced ✓

{{
  slug: 'descriptive-slug-topic',
  title: 'Specific Title 55-65 Chars — {TALLY_VERSION} {date.today().year}',
  tag: 'Guide',
  published: '{TODAY}',
  updated: '{TODAY}',
  description: '140-160 chars. Primary keyword first. Synergy benefit. Complete sentence.',
  keywords: 'primary keyword, bank statement tally, synergy automation tally',
  content: [
    {{ type: 'intro', text: 'Painful moment. Stakes. Synergy Automation solves this.' }},
    {{ type: 'h2', text: 'What is [Topic]?' }},
    {{ type: 'p', text: '60-80 words. Plain English.' }},
    {{ type: 'h2', text: 'How to [Action] in {TALLY_VERSION} — Step by Step' }},
    {{ type: 'steps', items: ['Step. Tally tip: ...', 'Step. Watch out: ...', '...', '...', '...'] }},
    {{ type: 'h2', text: 'Mistakes That Cost Indian CAs Hours' }},
    {{ type: 'list', items: ['Mistake → fix', '...', '...', '...'] }},
    {{ type: 'h2', text: 'How Synergy Automation Handles This' }},
    {{ type: 'p', text: 'Connect to hardest step. Upload Excel → review → post to Tally. Free. No XML.' }},
    {{ type: 'infographic', variant: 'steps', title: 'Process title 5-7 words', items: ['Label', 'Label', 'Label', 'Label', 'Label'] }},
    {{ type: 'faq', items: [
      {{ q: 'Primary keyword question?', a: 'Self-contained answer.' }},
      {{ q: 'Can Synergy Automation help with [topic]?', a: 'Self-contained. What it does. Free.' }},
      {{ q: 'Tally ERP 9 vs {TALLY_VERSION} for this?', a: 'Self-contained.' }},
      {{ q: 'Common mistake question?', a: 'Self-contained with fix.' }},
      {{ q: 'Time comparison — manual vs Synergy?', a: 'Self-contained with realistic numbers.' }}
    ]}}
  ]
}}
"""


# ─────────────────────────────────────────────
# STEP 3 — GENERATE ARTICLE (multi-provider)
# ─────────────────────────────────────────────
def generate_article(topic, videos_with_transcript, provider='gemini', mode=None):
    if mode is None:
        mode = detect_article_mode(topic)
    print(f'  Article mode: {mode}')
    prompt = build_prompt(topic, videos_with_transcript, mode=mode)

    if provider == 'gemini':
        return _generate_gemini(prompt)
    elif provider == 'openai':
        return _generate_openai(prompt)
    elif provider == 'claude':
        return _generate_claude(prompt)
    else:
        print(f'Unknown provider: {provider}. Using gemini.')
        return _generate_gemini(prompt)


def _generate_gemini(prompt):
    """FREE — Gemini 1.5 Flash. 1,500 requests/day free tier. Get key: aistudio.google.com"""
    try:
        from google import genai
        from google.genai import types
    except ImportError:
        print("ERROR: Run: pip install google-genai")
        sys.exit(1)

    if not GEMINI_API_KEY:
        print("ERROR: Set GEMINI_API_KEY — get free key at aistudio.google.com (no credit card)")
        sys.exit(1)

    client = genai.Client(api_key=GEMINI_API_KEY)
    for attempt in range(3):
        try:
            response = client.models.generate_content(
                model='gemini-2.5-flash-lite',
                contents=prompt,
                config=types.GenerateContentConfig(max_output_tokens=4000, temperature=0.7)
            )
            return _clean_article(response.text.strip())
        except Exception as e:
            err = str(e)
            if ('429' in err or '503' in err) and attempt < 2:
                wait = 40 + attempt * 20
                print(f'  Gemini busy ({err[:60]}) — waiting {wait}s before retry ({attempt+1}/3)...')
                time.sleep(wait)
            else:
                print(f'ERROR: Gemini generation failed: {e}')
                sys.exit(1)


def _clean_article(text):
    """Strip markdown code fences Gemini sometimes wraps output in."""
    text = text.strip()
    # Remove ```json ... ``` or ``` ... ``` wrappers
    if text.startswith('```'):
        text = re.sub(r'^```[a-z]*\n?', '', text)
        text = re.sub(r'\n?```$', '', text)
        text = text.strip()
    return text


def _generate_openai(prompt):
    """~₹0.20/article — GPT-4o-mini"""
    try:
        from openai import OpenAI
    except ImportError:
        print("ERROR: Run: pip install openai")
        sys.exit(1)

    if not OPENAI_API_KEY:
        print("ERROR: Set OPENAI_API_KEY — get key at platform.openai.com")
        sys.exit(1)

    client = OpenAI(api_key=OPENAI_API_KEY)
    resp = client.chat.completions.create(
        model='gpt-4o-mini',
        max_tokens=4000,
        messages=[{'role': 'user', 'content': prompt}]
    )
    return resp.choices[0].message.content.strip()


def _generate_claude(prompt):
    """~₹4.50/article — Claude claude-sonnet-4-6 (best quality, most expensive)"""
    try:
        import anthropic
    except ImportError:
        print("ERROR: Run: pip install anthropic")
        sys.exit(1)

    if not ANTHROPIC_API_KEY:
        print("ERROR: Set ANTHROPIC_API_KEY — get key at console.anthropic.com")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    message = client.messages.create(
        model='claude-sonnet-4-6',
        max_tokens=4000,
        messages=[{'role': 'user', 'content': prompt}]
    )
    return message.content[0].text.strip()


# ─────────────────────────────────────────────
# STEP 4 — SHOW PREVIEW + GET APPROVAL
# ─────────────────────────────────────────────
def show_preview(topic, article_js, videos):
    print('\n' + '='*60)
    print(f'TOPIC: {topic}')
    print('RESEARCHED FROM:')
    for v in videos:
        icon = '✓' if v['transcript'] else '✗'
        print(f'  {icon} {v["title"][:70]}')
    print('='*60)
    print('\nGENERATED ARTICLE (preview):')
    print('-'*60)

    # Extract title and slug for quick review
    slug_match = re.search(r'''["']?slug["']?\s*:\s*["']([^"']+)["']''', article_js)
    title_match = re.search(r'''["']?title["']?\s*:\s*["']([^"']+)["']''', article_js)
    desc_match = re.search(r'''["']?description["']?\s*:\s*["']([^"']+)["']''', article_js)

    if slug_match:
        print(f'  URL:   /blog/{slug_match.group(1)}')
    if title_match:
        print(f'  Title: {title_match.group(1)}')
    if desc_match:
        print(f'  Desc:  {desc_match.group(1)[:100]}')

    print('\n--- FULL CONTENT ---')
    # Show first 1500 chars
    preview = article_js[:1500]
    print(preview)
    if len(article_js) > 1500:
        print(f'\n  ... ({len(article_js) - 1500} more chars) ...')
    print('-'*60)

    print('\nOptions:')
    print('  y      — Approve and publish to develop branch')
    print('  n      — Skip this topic')
    print('  s      — Save draft for manual editing')
    print('  r      — Regenerate article')

    return input('\nYour choice (y/n/s/r): ').strip().lower()


# ─────────────────────────────────────────────
# STEP 5 — PUBLISH
# ─────────────────────────────────────────────
def check_topic_relevance(topic):
    """
    Ask Gemini: is this topic genuinely about Tally accounting workflows?
    Returns (is_relevant: bool, reason: str).
    Rejects topics like 'ITR filing on income tax portal' which are adjacent
    but not about Tally software usage.
    """
    prompt = (
        f'Topic: "{topic}"\n\n'
        'Is this topic genuinely about using Tally accounting software (TallyPrime / Tally ERP 9) '
        'for day-to-day accounting workflows — like entering vouchers, reconciling bank statements, '
        'configuring payroll, GST reports inside Tally, TDS entries in Tally, etc.?\n\n'
        'Answer NO if the topic is primarily about:\n'
        '- Filing returns on government portals (income tax portal, GST portal) — not Tally\n'
        '- Generic accounting/finance concepts unrelated to Tally software\n'
        '- Tax planning or investment advice\n'
        '- General ITR filing steps (these happen on the IT portal, not in Tally)\n\n'
        'Reply with exactly one line: YES or NO, followed by a colon and a brief reason.\n'
        'Example: YES: GST reports in TallyPrime are a core Tally workflow\n'
        'Example: NO: ITR filing is done on incometaxindia.gov.in, not in Tally'
    )
    result = _call_gemini(prompt, max_tokens=60, temperature=0.0)
    if not result:
        return True, 'Gemini unavailable — assuming relevant'
    line = result.strip().splitlines()[0]
    is_relevant = line.upper().startswith('YES')
    reason = line.split(':', 1)[-1].strip() if ':' in line else line
    return is_relevant, reason


def _send_telegram_approval(slug, article_js):
    """Send Telegram notification with article preview + Approve/Discard buttons."""
    try:
        sys.path.insert(0, str(Path(__file__).parent))
        from seo_telegram import send_approval_request
        title_match = re.search(r'''["']?title["']?\s*:\s*["']([^"']+)["']''', article_js)
        desc_match  = re.search(r'''["']?description["']?\s*:\s*["']([^"']+)["']''', article_js)
        title = title_match.group(1) if title_match else slug
        desc  = desc_match.group(1) if desc_match else ''
        send_approval_request(slug, title, desc)
        print('  Telegram: Approval request sent. Article will go live when you approve.')
        print('  No Telegram approval = stays on develop only (not on master).')
    except Exception as e:
        print(f'  Telegram notification skipped: {e}')
        preview_url = f'https://develop.synergy-public-site.pages.dev/blog/{slug}'
        print(f'  Manual review: {preview_url}')
        print(f'  To publish: git checkout master && git merge develop && git push origin master')


def _sanitize_js_quotes(text):
    """Replace AI-generated curly/smart quotes with straight ASCII quotes."""
    return (text
        .replace('‘', "'").replace('’', "'")   # '' → ''
        .replace('“', '"').replace('”', '"')   # "" → ""
    )


def publish_article(article_js, commit=True, push=False):
    """Write article to all files. commit=False skips git (GitHub Actions commits separately)."""
    article_js = _sanitize_js_quotes(article_js)
    slug_match = re.search(r'''["']?slug["']?\s*:\s*["']([^"']+)["']''', article_js)
    if not slug_match:
        print('ERROR: Cannot find slug in article. Save as draft and check manually.')
        return False

    slug = slug_match.group(1)
    print(f'\nWriting /blog/{slug} to files...')

    # ── blogData.js ──
    blog_data = BLOG_DATA_FILE.read_text(encoding='utf-8')

    # Duplicate check — never publish the same slug twice
    if f"slug: '{slug}'" in blog_data or f'"slug": "{slug}"' in blog_data:
        print(f'  SKIP: slug "{slug}" already exists in blogData.js — article not duplicated.')
        return False

    # Find the closing ]; of the array (file may have functions after it)
    close_idx = blog_data.rfind('\n];')
    if close_idx == -1:
        print('  ERROR: blogData.js format unexpected — cannot find closing ];')
        return False
    chunk_before = blog_data[:close_idx].rstrip()
    if not chunk_before.endswith(','):
        chunk_before += ','
    chunk_after = blog_data[close_idx + 1:]  # keeps ]; and everything after (exports, functions)
    new_blog_data = chunk_before + f'\n  {article_js}\n' + chunk_after
    BLOG_DATA_FILE.write_text(new_blog_data, encoding='utf-8')
    print('  ✓ blogData.js updated')

    # sitemap.js auto-generates from blogData.js — no manual update needed

    if not commit:
        print(f'  ✓ Files written. Slug: {slug}')
        # Write slug to a file so the GitHub Actions step can read it
        (REPO_ROOT / '.seo_last_slug').write_text(slug, encoding='utf-8')
        return True

    # ── git commit (local use only) ──
    files = [
        str(BLOG_DATA_FILE),
    ]
    subprocess.run(['git', 'add'] + files, cwd=REPO_ROOT, check=True)
    commit_msg = f'feat(seo): add {slug} article via YouTube pipeline'
    result = subprocess.run(
        ['git', 'commit', '-m', commit_msg],
        cwd=REPO_ROOT, capture_output=True, text=True
    )
    if result.returncode == 0:
        print(f'  ✓ Committed: {commit_msg}')
    else:
        print(f'  WARNING: git commit issue: {result.stderr}')

    print(f'\n✅ Done! /blog/{slug} is ready.')

    if push:
        branch_result = subprocess.run(
            ['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
            cwd=REPO_ROOT, capture_output=True, text=True
        )
        branch = branch_result.stdout.strip() or 'develop'
        push_result = subprocess.run(
            ['git', 'push', 'origin', branch],
            cwd=REPO_ROOT, capture_output=True, text=True
        )
        if push_result.returncode == 0:
            print(f'  ✓ Pushed to origin/{branch}')
            print(f'  Preview: https://develop.synergy-public-site.pages.dev/blog/{slug}')
            # Send Telegram approval request (non-blocking — if no token, just prints instructions)
            _send_telegram_approval(slug, article_js)
        else:
            print(f'  WARNING: git push failed: {push_result.stderr}')
            print(f'  Run manually: git push origin {branch}')
    else:
        print('Next step: git push origin develop')
        print('Then merge develop → master to go live on synergyfuturecorp.com')
    return True


# ─────────────────────────────────────────────
# DRAFT SAVE / PUBLISH FROM DRAFT
# ─────────────────────────────────────────────
def save_draft(topic, article_js):
    DRAFTS_DIR.mkdir(exist_ok=True)
    safe_topic = re.sub(r'[^a-z0-9]+', '-', topic.lower()).strip('-')
    draft_path = DRAFTS_DIR / f'draft-{safe_topic}.js'
    draft_path.write_text(article_js, encoding='utf-8')
    print(f'\nDraft saved: {draft_path}')
    print('Edit it, then run:')
    print(f'  python scripts/seo_youtube_pipeline.py --publish "{draft_path}"')


def publish_from_draft(draft_path):
    path = Path(draft_path)
    if not path.exists():
        print(f'ERROR: Draft not found: {draft_path}')
        sys.exit(1)
    article_js = path.read_text(encoding='utf-8').strip()
    success = publish_article(article_js)
    if success:
        path.unlink()
        print('Draft file removed after publish.')


# ─────────────────────────────────────────────
# TOPIC QUEUE (for daily/recurring use)
# ─────────────────────────────────────────────
def get_next_topic_from_queue():
    if not QUEUE_FILE.exists():
        print(f'No queue file found at {QUEUE_FILE}')
        print('Create it with one topic per line.')
        sys.exit(1)

    done = set()
    if DONE_FILE.exists():
        done = set(DONE_FILE.read_text(encoding='utf-8').splitlines())

    topics = [
        line.strip()
        for line in QUEUE_FILE.read_text(encoding='utf-8').splitlines()
        if line.strip() and not line.startswith('#') and line.strip() not in done
    ]

    if not topics:
        print('All topics in queue have been processed.')
        print(f'Add more topics to {QUEUE_FILE}')
        sys.exit(0)

    return topics[0]


def mark_topic_done(topic):
    with open(DONE_FILE, 'a', encoding='utf-8') as f:
        f.write(topic + '\n')


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────
def run_pipeline(topic, provider='gemini', auto=False, push=False):
    """
    auto=True  — no interactive prompt, just write files (used by GitHub Actions).
                 Caller is responsible for committing/PR after this returns True.
    auto=False — interactive y/n/s/r approval (local use).
    """
    print(f'\nSearching YouTube: "{topic} tally india" ...')
    videos = search_videos(topic, max_results=6)

    if not videos:
        print('No videos found. Try a different topic.')
        return False

    print(f'Found {len(videos)} videos. Fetching transcripts...')
    for v in videos:
        v['transcript'] = get_transcript(v['id'])
        icon = '✓' if v['transcript'] else '✗'
        print(f'  {icon} {v["title"][:65]}')

    usable = [v for v in videos if v['transcript']]
    no_caption = [v for v in videos if not v.get('transcript')]
    if no_caption:
        # Stage 3: Audio download → Gemini Files API (primary method, any video length)
        label = 'No captions found.' if not usable else 'Enriching with audio...'
        print(f'{label} Downloading audio for Gemini analysis...')
        for v in no_caption[:6]:  # Up to 6 videos — skip 403-blocked ones, get richer research
            print(f'  {v["title"][:65]}')
            content = get_audio_transcript_gemini(v['id'], v['title'])
            if content:
                v['transcript'] = content
                print(f'    ✓ {len(content)} chars extracted from audio')
            else:
                if not v.get('transcript'):
                    v['transcript'] = f"Video title: {v['title']}\nDescription: {v['description']}"
                    print(f'    ✗ Using title/description only')

    usable = [v for v in videos if v.get('transcript')]

    mode = detect_article_mode(topic)
    print(f'\n Generating article via {provider} from {len(usable)} video(s)... [mode: {mode}]')
    article_js = generate_article(topic, usable, provider=provider, mode=mode)

    if auto:
        # commit=True when --push (local automation), commit=False for GitHub Actions
        return publish_article(article_js, commit=push, push=push)

    while True:
        choice = show_preview(topic, article_js, videos)

        if choice == 'y':
            success = publish_article(article_js, push=push)
            return success

        elif choice == 'n':
            print('Skipped.')
            return False

        elif choice == 's':
            save_draft(topic, article_js)
            return False

        elif choice == 'r':
            print('\nRegenerating...')
            article_js = generate_article(topic, usable, provider=provider, mode=mode)

        else:
            print('Invalid choice. Enter y / n / s / r')


def main():
    args = sys.argv[1:]

    # Parse --ai <provider> flag
    provider = 'gemini'
    if '--ai' in args:
        idx = args.index('--ai')
        if idx + 1 < len(args):
            provider = args[idx + 1]
            args = [a for i, a in enumerate(args) if i != idx and i != idx + 1]

    # Parse --auto flag (non-interactive, used by GitHub Actions)
    auto = '--auto' in args
    if auto:
        args = [a for a in args if a != '--auto']

    # Parse --push flag (auto-push to GitHub after commit, local use)
    push = '--push' in args
    if push:
        args = [a for a in args if a != '--push']

    print(f'AI provider: {provider}{"  [AUTO]" if auto else ""}{"  [PUSH]" if push else ""}')

    # --publish path/to/draft.js
    if args and args[0] == '--publish':
        if len(args) < 2:
            print('Usage: python seo_youtube_pipeline.py --publish path/to/draft.js')
            sys.exit(1)
        publish_from_draft(args[1])
        return

    # --trending  (discover topic from YouTube trending videos)
    if args and args[0] == '--trending':
        print('Discovering trending topic from YouTube...')
        topic = get_trending_topic()
        if not topic:
            print('Could not discover trending topic. Falling back to queue.')
            topic = get_next_topic_from_queue()

        # Relevance check — reject topics not genuinely about Tally workflows
        print(f'Checking relevance of "{topic}"...')
        is_relevant, reason = check_topic_relevance(topic)
        if not is_relevant:
            print(f'  SKIP (not Tally-related): {reason}')
            mark_topic_done(topic)  # avoid picking same topic again
            print('  Trying queue fallback...')
            topic = get_next_topic_from_queue()
            print(f'  Queue topic: "{topic}"')

        print(f'Topic: "{topic}"')
        success = run_pipeline(topic, provider=provider, auto=auto, push=push)
        if success:
            mark_topic_done(topic)
        return

    # --queue  (pick next topic from static queue file)
    if args and args[0] == '--queue':
        topic = get_next_topic_from_queue()
        print(f'Queue topic: "{topic}"')
        success = run_pipeline(topic, provider=provider, auto=auto, push=push)
        if success:
            mark_topic_done(topic)
        return

    # Direct topic from command line
    if args:
        topic = ' '.join(args)
    else:
        topic = input('Enter topic: ').strip()

    if not topic:
        print('No topic provided.')
        sys.exit(1)

    run_pipeline(topic, provider=provider, auto=auto, push=push)


if __name__ == '__main__':
    main()
